---

- name: Create PostgreSQL databases if no present   
  become_user: postgres 
  postgresql_db:
    name: devops_db            
    state: present

 
- name: Create nick user for Postgres   
  become_user: postgres 
  postgresql_user:     
    name: postgres
    password: postgres2020   
    encrypted: yes   
    state: present
  


- name: Create table if not exist  
  become_user: postgres 
  postgresql_table:
    db: devops_db    
    name: accounts
    columns:
      - user_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY
      - username VARCHAR(50) UNIQUE NOT NULL
      - password VARCHAR(255) NOT NULL
      - email VARCHAR(50) UNIQUE NOT NULL
    state: present