---
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_only: yes

        
- name: Install repo package
  yum:
    name: "{{ repo_package }}"    
    state: present


- name: Install packages  
  yum:     
    name: "{{ packages }}" 
    enablerepo: "{{ repo_name }}"
    state: present

