---
- name: Include task to install packages for Web
  include: installation.yaml

- name: Start and enable service  
  service:
    name: "{{ service_name }}" 
    state: "{{ state }}" 
    enabled: "{{ enable }}" 


- name: Open firewall port for service  
  firewalld:
    service: "{{ service_name_firewall }}" 
    zone: public
    immediate: yes # this is the firewall-cmd --reload
    permanent: true
    state: enabled


- name: Configure SELinux with boolean   
  seboolean:
    name: "{{ service_name_selinux }}" 
    state: true
    persistent: yes
  
    
- name: Clone a repo with separate git directory
  git:
    repo: "{{ git_repo_name }}"  
    dest: /home/ansible/{{ git_folder_name }}
    update: no


- name: Copy files between directories 
  copy:
    src: "{{ src_path }}"
    dest: "{{ dest_path }}"
    remote_src: yes 
    
  

- name: Find .php files
  find:
    paths: /var/www/html/
    patterns: "*.php"
  register: php


- name: Replace host in .php files
  replace:
    path: "{{ item.path }}"
    regexp: '^(.*)host=postgres(.*)$'
    replace: '\1host=10.0.0.188\2'
  with_items: "{{ php.files }}"  



    

  