---
- name: Include task to install packages for Web
  include: installation.yaml


- name: Include task to configure Firewall and Selinux
  include: security.yaml
  

- name: Start and enable service  
  service:
    name: "{{ service_name }}" 
    state: "{{ state }}" 
    enabled: "{{ enable }}" 
  
    
- name: Clone a repo with separate git directory
  git:
    repo: "{{ git_repo_name }}"  
    dest: /home/ansible/{{ git_folder_name }}
    update: no


- name: Check if file already exists
  stat:
    path: /var/www/html/login.php
  register: files


- name: Copy files between directories     
  copy:    
    remote_src: yes
    src: "{{ src_path }}"
    dest: "{{ dest_path }}"  
  notify: 
    - Find files
    - Replace host  
  when: files.stat.exists == False



    

  