---
- name: Include task to install packages for DB
  include: installation.yaml
  

- name: Include task to configure Firewall and Selinux
  include: security.yaml


- name: Check if database is already initialized  
  stat:
    path: "/var/lib/pgsql/12/data/PG_VERSION"
  register: init_status


- name: Initialize the master database  
  shell: /usr/pgsql-12/bin/postgresql-12-setup initdb
  when: init_status.stat.exists == False

  
- name: Start and enable service  
  service:
    name: "{{ service_name }}" 
    state: started
    enabled: yes
  when: init_status.stat.exists == True


- name: Add new configuration to "postgresql.conf" - listen All  
  blockinfile:
    create: yes
    dest: "{{ postgresql_config_path }}/postgresql.conf" 
    block: |
      listen_addresses = '*' 
  notify: Restart service 
    

- name: Configure host based authentication 
  copy:
    src: "pg_hba.conf"
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0600
  notify: Restart service
  
  
    
- name: Include task to create PG_roles and PG_databases
  include: databases.yaml
  


      

    

