---

- name: Install packages
  yum: 
    enablerepo: "{{ repo_name }}" 
    name: "{{ packages }}" 
    state: present


- name: Open firewall port for service
  become: yes
  firewalld:
    service: "{{ firewall_service }}" 
    zone: public
    immediate: yes # this is the firewall-cmd --reload
    permanent: true
    state: enabled

- name: Include task to setup postgres
  include: setup_db.yaml
  


      

    

