---

- name: Install packages  
  yum: 
    enablerepo: "{{ repo_name }}" 
    name: "{{ packages }}" 


- name: Start and enable service  
  service:
    name: "{{ service_name }}" 
    state: "{{ state }}" 
    enabled: "{{ enable }}" 


- name: Open firewall port for service  
  firewalld:
    service: "{{ service_name_firewall }}" 
    zone: public
    immediate: yes # this is the firewall-cmd --reload
    permanent: true
    state: enabled


- name: Include task to setup web
  include: setup_web.yaml
  