---
#install packages

packages: 
  #- "*"    
  - epel-release  
  - postgresql12-server  
  - postgresql12-contrib
  - python3-psycopg2
  - postgresql-libs
  - postgresql-devel
  - python-psycopg2


#Install and enable repo

repo_package: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
repo_name: pgdg12  

#start and enable service 

service_name: postgresql-12

#open firewall port for service

firewall_service: postgresql




  




